version: '3.5'

services:
  api:
    container_name: leadersoft_2020_1_api
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./backend:/usr/src/app
